# 此为草稿代码

## Conv2dLSTM 草稿

In [1]:
import torch
import torch.nn as nn

In [2]:
channels = 16          # 通道数
hidden_dim = 32        # 隐藏层
batch_size = 2         
t = 2                  # 序列长度
height, width = 2, 3   # 图像宽高

In [3]:
conv = nn.Conv2d(in_channels = channels + hidden_dim,
                 out_channels = 4 * hidden_dim,          # 所以这里的 4 表示有四个门
                 kernel_size=(3, 3),
                 padding=(1, 1), 
                 bias=True)

In [4]:
x = torch.rand((batch_size, channels, height, width))
h = torch.zeros(batch_size, hidden_dim, height, width)

print(x.size())
print(h.size())
# 按照通道维度进行拼接
combined = torch.cat([x, h], dim=1)
print(combined.size())

torch.Size([2, 16, 2, 3])
torch.Size([2, 32, 2, 3])
torch.Size([2, 48, 2, 3])


In [5]:
combined_conv = conv(combined)
# 取出四个门的值
cc_i, cc_f, cc_o, cc_g = torch.split(combined_conv, hidden_dim, dim=1)

In [6]:
# 4 * 32 = 128
print(combined_conv.size())

torch.Size([2, 128, 2, 3])


In [7]:
print(cc_i.size())
print(cc_f.size())
print(cc_o.size())
print(cc_g.size())

torch.Size([2, 32, 2, 3])
torch.Size([2, 32, 2, 3])
torch.Size([2, 32, 2, 3])
torch.Size([2, 32, 2, 3])


In [8]:
a = torch.rand((2, 2))
b = torch.rand((2, 2))
print(a)
print(b)
print(a * b)

tensor([[0.6768, 0.4090],
        [0.1231, 0.1319]])
tensor([[0.7860, 0.0229],
        [0.8491, 0.6703]])
tensor([[0.5320, 0.0094],
        [0.1046, 0.0884]])


In [9]:
# 所以门那里是相同维度的矩阵对应元素相乘
a = cc_f * h
print(a.size())

torch.Size([2, 32, 2, 3])


## torch.stack 用法

所以上一层的输出 stack 后，能输入到下一层

In [10]:
a = torch.rand((32, 64, 128, 128))
b = torch.rand((32, 64, 128, 128))
ls = []
ls.append(a)
ls.append(b)
a = torch.stack(ls, dim=1)
print(a.size())

torch.Size([32, 2, 64, 128, 128])


## Conv3dLSTM 草稿

In [2]:
in_channels = 2
out_channels = 12
hidden_dim = 16
kernel_size = (3, 3, 3)
deepth = 10
height, width = 50, 50
dilation = (2, 2, 2)
batch_size = 2

# 填充维度计算公式
# https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html
padding = tuple(dilation[i] * (kernel_size[i] - 1) // 2 for i in range(3))

In [3]:
x = torch.rand((batch_size, in_channels, deepth, height, width))
h = torch.rand((batch_size, hidden_dim, deepth, height, width))

In [4]:
model = nn.Conv3d(in_channels=in_channels + hidden_dim, 
              out_channels=4 * hidden_dim,
              kernel_size=kernel_size, 
              padding=padding,
              dilation=dilation)

In [5]:
combined = torch.cat([x, h], dim=1)
print(combined.size())

torch.Size([2, 18, 10, 50, 50])


In [6]:
print(model)

Conv3d(18, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(2, 2, 2), dilation=(2, 2, 2))


In [10]:
combined_conv = model(combined)
print(combined_conv.size())
# 取出四个门的值
cc_i, cc_f, cc_o, cc_g = torch.split(combined_conv, hidden_dim, dim=1)

torch.Size([2, 64, 10, 50, 50])


In [11]:
print(combined_conv.size())
print(cc_i.size())
print(cc_f.size())
print(cc_o.size())
print(cc_g.size())

torch.Size([2, 64, 10, 50, 50])
torch.Size([2, 16, 10, 50, 50])
torch.Size([2, 16, 10, 50, 50])
torch.Size([2, 16, 10, 50, 50])
torch.Size([2, 16, 10, 50, 50])


In [42]:
a = cc_f * h
print(a.size())

torch.Size([2, 16, 10, 50, 50])


In [14]:
for i in range (0, 4-4, 1):
    print(i, i + 4)